"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import { HikariProviders, globalStyles } from "hikari-ui";
import classNames from "classnames";
import { Header } from "@/components/common/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  globalStyles();

  return (
    <HikariProviders>
      <html lang="en">
        <body className={inter.className}>
          <div
            className={classNames("flex flex-col items-center", "min-h-screen")}
          >
            <Header />
            {children}
          </div>
        </body>
      </html>
    </HikariProviders>
  );
}
